### ISSUE TITLE
adapters don't work when stringified in a virtual module

### ISSUE THREAD

**Issue by tony-sull** [nowaythatworked/auth-astro#21]
When the integration config is converted to a virutal module in [config.ts](https://github.com/nowaythatworked/auth-astro/blob/8001d96a17718ba70908a626e8bcc91c2b7435af/src/config.ts#L17), the `adapter` instance is lost when `JSON.stringify()` can't stringify the adapter's functions

I'm hoping this isn't an issue with wrapping everything up in an Astro integration, the `astro add auth-astro` flow makes for a really nice developer experience!

I think the main challenge is how the various provider and adapter packages are setup.  To go through a Vite virtual module the integration really needs to know the package name used for providers an integrations rather than an object instance.  That would allow the `config.ts` virtual module to handle building the logic for actually creating instances in the virtual module itself.

**Contributing**

I'm happy to work on a PR if there's a direction you have in mind!  I'm just learning this codebase (along with the rest of Auth.js) -  curious if you all have thoughts on a different solution I hadn't considered yet before I dig in too far!

**Comment by tony-sull** [comment]
One idea here that I've been able to prototype locally, config for Auth.js could be moved out to it's own config file like `auth.config.mjs`

**`/auth.config.mjs`**
```js
import GitHub from '@auth/core/providers/github'

export default {
    providers: [
        GitHub({
            clientId: import.meta.env.GITHUB_CLIENT_ID,
            clientSecret: import.meta.env.GITHUB_CLIENT_SECRET
        })
    ]
}
```

This would let the `auth:config` virtual module to resolve the config object *after* the Astro config file executes and the `auth-astro` is running in Vite land

```ts
export const virtualConfigModule = (configFile: string): PluginOption => {
	return {
		name: 'auth-astro-config',
		load: (id) => {
			if (id === resolvedId) {
				return `import authConfig from "${configFile}"; export default authConfig;`
			}
		},
	}
}
```

**Comment by TheOtterlord** [comment]
Weird, I sent a message yesterday, but it's not here.

I definitely agree a separate config file is the way to go (which I guess is obvious now because of the PR). I've tried a few things from analyzing the astro config file, to making an additional required export statement, but everything I've tried around the main config file ends up being a sub-par developer experience, or introduces weird side-effects in more complex config files.

I'm actually really happy with this solution though, and hopefully it shouldn't be long before people can start migrating.
