### ISSUE TITLE
ReferenceError: exports is not defined     at /node_modules/.pnpm/cookie@0.5.0/node_modules/cookie/index.js:15:1

### ISSUE THREAD

**Issue by arjunindia** [nowaythatworked/auth-astro#9]
I got this while trying to set this up. I'm using the vercel adapter.

**Comment by TheOtterlord** [comment]
Adding this to your `astro.config.mjs` should fix this. I'll look for a better solution, but if I can't find one, I'll add this to the docs.
```mjs
  vite: {
    ssr: {
      noExternal: ['auth-astro']
    },
  }
```

**Comment by arjunindia** [comment]
Also the above solution doesnt fix the issue on pnpm

**Comment by TheOtterlord** [comment]
ooh ok, thanks. I'll try to replicate this and see if we can fix whatever pnpm is doing

**Comment by gadzan** [comment]
> I found out what the problem is I actually used pnpm instead of npm and npm works

I solved this by `pnpm add cookie`, 

Because of import cookie without installing deps：
https://github.com/nowaythatworked/auth-astro/blob/8191f11617f679b1450045a33e8b7fd8d9d0fcb2/index.ts#L29

**Comment by TheOtterlord** [comment]
OH

We only have the types for `cookie` we don't have it as a dependency. I guess we never ran into this before, because `@auth/core` has it as a dependency.

Thanks so much for looking into this, I've been pretty busy recently, but I'm also in the process of prepping v2 for launch. I'll try to get this added as a dependency ASAP.

**Comment by nowaythatworked** [comment]
Thank you all for the help. The new version `1.0.6` was just published. It adds cookie as a dependency which should fix this issue.
